// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/system-map/SystemMap.tsx": () => import("../components/mockups/system-map/SystemMap.tsx")
};
